// flow-typed signature: 02e100fd8bd5e661609686181ed392a2
// flow-typed version: <<STUB>>/electron-json-storage_v^4.1.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-json-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-json-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-json-storage/lib/lock' {
  declare module.exports: any;
}

declare module 'electron-json-storage/lib/storage' {
  declare module.exports: any;
}

declare module 'electron-json-storage/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-json-storage/stress/process' {
  declare module.exports: any;
}

declare module 'electron-json-storage/tests/storage.spec' {
  declare module.exports: any;
}

declare module 'electron-json-storage/tests/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-json-storage/lib/lock.js' {
  declare module.exports: $Exports<'electron-json-storage/lib/lock'>;
}
declare module 'electron-json-storage/lib/storage.js' {
  declare module.exports: $Exports<'electron-json-storage/lib/storage'>;
}
declare module 'electron-json-storage/lib/utils.js' {
  declare module.exports: $Exports<'electron-json-storage/lib/utils'>;
}
declare module 'electron-json-storage/stress/process.js' {
  declare module.exports: $Exports<'electron-json-storage/stress/process'>;
}
declare module 'electron-json-storage/tests/storage.spec.js' {
  declare module.exports: $Exports<'electron-json-storage/tests/storage.spec'>;
}
declare module 'electron-json-storage/tests/utils.spec.js' {
  declare module.exports: $Exports<'electron-json-storage/tests/utils.spec'>;
}
