// flow-typed signature: 2eba57b235fb651302170d27b4a42404
// flow-typed version: <<STUB>>/fs-jetpack_v^2.2.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-jetpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-jetpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-jetpack/benchmark/copy' {
  declare module.exports: any;
}

declare module 'fs-jetpack/benchmark/remove' {
  declare module.exports: any;
}

declare module 'fs-jetpack/benchmark/utils' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/append' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/copy' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/dir' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/exists' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/file' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/find' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/inspect_tree' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/inspect' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/jetpack' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/list' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/move' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/read' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/remove' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/rename' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/streams' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/symlink' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/matcher' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/mode' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/promisify' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/tree_walker' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/validate' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/write' {
  declare module.exports: any;
}

declare module 'fs-jetpack/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-jetpack/benchmark/copy.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/copy'>;
}
declare module 'fs-jetpack/benchmark/remove.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/remove'>;
}
declare module 'fs-jetpack/benchmark/utils.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/utils'>;
}
declare module 'fs-jetpack/lib/append.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/append'>;
}
declare module 'fs-jetpack/lib/copy.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/copy'>;
}
declare module 'fs-jetpack/lib/dir.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/dir'>;
}
declare module 'fs-jetpack/lib/exists.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/exists'>;
}
declare module 'fs-jetpack/lib/file.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/file'>;
}
declare module 'fs-jetpack/lib/find.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/find'>;
}
declare module 'fs-jetpack/lib/inspect_tree.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/inspect_tree'>;
}
declare module 'fs-jetpack/lib/inspect.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/inspect'>;
}
declare module 'fs-jetpack/lib/jetpack.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/jetpack'>;
}
declare module 'fs-jetpack/lib/list.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/list'>;
}
declare module 'fs-jetpack/lib/move.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/move'>;
}
declare module 'fs-jetpack/lib/read.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/read'>;
}
declare module 'fs-jetpack/lib/remove.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/remove'>;
}
declare module 'fs-jetpack/lib/rename.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/rename'>;
}
declare module 'fs-jetpack/lib/streams.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/streams'>;
}
declare module 'fs-jetpack/lib/symlink.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/symlink'>;
}
declare module 'fs-jetpack/lib/utils/fs.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/fs'>;
}
declare module 'fs-jetpack/lib/utils/matcher.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/matcher'>;
}
declare module 'fs-jetpack/lib/utils/mode.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/mode'>;
}
declare module 'fs-jetpack/lib/utils/promisify.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/promisify'>;
}
declare module 'fs-jetpack/lib/utils/tree_walker.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/tree_walker'>;
}
declare module 'fs-jetpack/lib/utils/validate.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/validate'>;
}
declare module 'fs-jetpack/lib/write.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/write'>;
}
declare module 'fs-jetpack/main.js' {
  declare module.exports: $Exports<'fs-jetpack/main'>;
}
