export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'
export const SET_DIRECTORY_PATH = 'SET_DIRECTORY_PATH'
export const GET_DIRECTORY_PROJECTS = 'GET_DIRECTORY_PROJECTS'
export const RECEIVE_DIRECTORY_PROJECTS = 'RECEIVE_DIRECTORY_PROJECTS'
export const JSON_DOES_NOT_EXIST = 'JSON_DOES_NOT_EXIST'
export const CREATE_NEW_PROJECT_JSON_FILE = 'CREATE_NEW_PROJECT_JSON_FILE'
export const UPDATE_DIRECTORY_PROJECTS = 'UPDATE_DIRECTORY_PROJECTS'
export const PROJECTS_LOADING = 'PROJECTS_LOADING'

export const SET_APP_METADATA_PATH = 'SET_APP_METADATA_PATH'

export const LOAD_APP_METADATA_REQUESTED = 'LOAD_APP_METADATA_REQUESTED'
export const LOAD_APP_METADATA_SUCCEEDED = 'LOAD_APP_METADATA_SUCCEEDED'
export const LOAD_APP_METADATA_FAILED = 'LOAD_APP_METADATA_FAILED'

export const CREATE_APP_METADATA_REQUESTED = 'CREATE_APP_METADATA_REQUESTED'
export const CREATE_APP_METADATA_SUCCEEDED = 'CREATE_APP_METADATA_SUCCEEDED'
export const CREATE_APP_METADATA_FAILED = 'CREATE_APP_METADATA_FAILED'

export const LOAD_PROJECT_METADATA_REQUESTED = 'LOAD_PROJECT_METADATA_REQUESTED'
export const LOAD_PROJECT_METADATA_SUCCEEDED = 'LOAD_PROJECT_METADATA_SUCCEEDED'
export const LOAD_PROJECT_METADATA_FAILED = 'LOAD_PROJECT_METADATA_FAILED'

export const CREATE_PROJECT_METADATA_REQUESTED = 'CREATE_PROJECT_METADATA_REQUESTED'
export const CREATE_PROJECT_METADATA_SUCCEEDED = 'CREATE_PROJECT_METADATA_SUCCEEDED'
export const CREATE_PROJECT_METADATA_FAILED = 'CREATE_PROJECT_METADATA_FAILED'

