export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'
export const SET_DIRECTORY_PATH = 'SET_DIRECTORY_PATH'
export const GET_DIRECTORY_PROJECTS = 'GET_DIRECTORY_PROJECTS'
export const RECIEVE_DIRECTORY_PROJECTS = 'RECIEVE_DIRECTORY_PROJECTS'