export const SET_APP_METADATA_PATH = 'SET_APP_METADATA_PATH'

export const LOAD_APP_METADATA_REQUESTED = 'LOAD_APP_METADATA_REQUESTED'
export const LOAD_APP_METADATA_SUCCEEDED = 'LOAD_APP_METADATA_SUCCEEDED'
export const LOAD_APP_METADATA_FAILED = 'LOAD_APP_METADATA_FAILED'

export const CREATE_APP_METADATA_REQUESTED = 'CREATE_APP_METADATA_REQUESTED'
export const CREATE_APP_METADATA_SUCCEEDED = 'CREATE_APP_METADATA_SUCCEEDED'
export const CREATE_APP_METADATA_FAILED = 'CREATE_APP_METADATA_FAILED'

export const LOAD_PROJECT_METADATA_REQUESTED = 'LOAD_PROJECT_METADATA_REQUESTED'
export const LOAD_PROJECT_METADATA_SUCCEEDED = 'LOAD_PROJECT_METADATA_SUCCEEDED'
export const LOAD_PROJECT_METADATA_FAILED = 'LOAD_PROJECT_METADATA_FAILED'

export const CREATE_PROJECT_METADATA_REQUESTED = 'CREATE_PROJECT_METADATA_REQUESTED'
export const CREATE_PROJECT_METADATA_SUCCEEDED = 'CREATE_PROJECT_METADATA_SUCCEEDED'
export const CREATE_PROJECT_METADATA_FAILED = 'CREATE_PROJECT_METADATA_FAILED'

export const LOAD_CURRENT_PROJECT_REQUESTED = 'LOAD_CURRENT_PROJECT_REQUESTED'
export const LOAD_CURRENT_PROJECT_SUCCEEDED = 'LOAD_CURRENT_PROJECT_SUCCEEDED'
export const LOAD_CURRENT_PROJECT_FAILED = 'LOAD_CURRENT_PROJECT_FAILED'


export const UPDATE_NEW_PROJECT_FORM = 'UPDATE_NEW_PROJECT_FORM'